apiVersion: apps/v1
kind: Deployment
metadata:
  name: PaymentExternal
  labels:
    app: PaymentExternal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PaymentExternal
  template:
    metadata:
      labels:
        app: PaymentExternal
    spec:
      containers:
        - name: PaymentExternal
          image: username/PaymentExternal:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5