apiVersion: apps/v1
kind: Deployment
metadata:
  name: SMSExternal
  labels:
    app: SMSExternal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SMSExternal
  template:
    metadata:
      labels:
        app: SMSExternal
    spec:
      containers:
        - name: SMSExternal
          image: username/SMSExternal:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5